import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { fileURLToPath } from "node:url";
import {
  assertAccent,
  assertAppName,
  assertCapabilities,
  assertSafeSlug,
  GeneratorError,
} from "./validate";

const SKIP_NAMES = new Set([
  "node_modules",
  ".next",
  ".turbo",
  "dist",
  ".env",
  ".env.local",
  "AGENTS.md",
  "CLAUDE.md",
]);

type Answers = {
  slug: string;
  name: string;
  description: string;
  accent: string;
  capabilities: string[];
  force: boolean;
};

function repoRoot(): string {
  return join(dirname(fileURLToPath(import.meta.url)), "../../..");
}

function parseArgs(argv: string[]): Partial<Answers> & { slug?: string; yes?: boolean } {
  const args = argv.slice(2);
  const result: Partial<Answers> & { slug?: string; yes?: boolean } = { capabilities: [] };
  for (let i = 0; i < args.length; i += 1) {
    const token = args[i];
    if (!token) continue;
    if (token === "--yes" || token === "-y") {
      result.yes = true;
      continue;
    }
    if (token === "--force") {
      result.force = true;
      continue;
    }
    if (token === "--name") {
      result.name = args[i + 1];
      i += 1;
      continue;
    }
    if (token === "--description") {
      result.description = args[i + 1];
      i += 1;
      continue;
    }
    if (token === "--accent") {
      result.accent = args[i + 1];
      i += 1;
      continue;
    }
    if (token === "--capabilities") {
      result.capabilities = (args[i + 1] ?? "")
        .split(",")
        .map((value) => value.trim())
        .filter(Boolean);
      i += 1;
      continue;
    }
    if (!token.startsWith("-") && !result.slug) {
      result.slug = token;
    }
  }
  return result;
}

function titleFromSlug(slug: string): string {
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

async function promptMissing(partial: ReturnType<typeof parseArgs>): Promise<Answers> {
  const rl = createInterface({ input, output });
  const ask = async (question: string, fallback: string) => {
    if (!process.stdin.isTTY || partial.yes) {
      return fallback;
    }
    const value = await rl.question(`${question} [${fallback}] `);
    return value.trim() || fallback;
  };

  try {
    const slug = assertSafeSlug(partial.slug ?? (await ask("App slug", "newmini")));
    const name = assertAppName(partial.name ?? (await ask("App name", titleFromSlug(slug))));
    const description =
      (partial.description ??
        (await ask("Description", `${name} is a Telegram Mini App generated by MiniFactory.`))).trim();
    if (!description) {
      throw new GeneratorError("Description cannot be empty.");
    }
    const accent = assertAccent(partial.accent ?? (await ask("Accent color", "#2481cc")));
    const capabilitiesRaw =
      partial.capabilities && partial.capabilities.length > 0
        ? partial.capabilities
        : (await ask("Capabilities (comma-separated)", "telegramAuth,database,referrals"))
            .split(",")
            .map((value) => value.trim())
            .filter(Boolean);
    const capabilities = assertCapabilities(capabilitiesRaw);
    rl.close();
    return { slug, name, description, accent, capabilities, force: Boolean(partial.force) };
  } catch (error) {
    rl.close();
    throw error;
  }
}

function copyDir(from: string, to: string) {
  mkdirSync(to, { recursive: true });
  for (const entry of readdirSync(from)) {
    if (SKIP_NAMES.has(entry)) {
      continue;
    }
    const source = join(from, entry);
    const target = join(to, entry);
    const stats = statSync(source);
    if (stats.isDirectory()) {
      copyDir(source, target);
    } else {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, readFileSync(source));
    }
  }
}

function escape(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

function writeAppConfig(targetDir: string, answers: Answers) {
  const capabilities = answers.capabilities.map((item) => `"${item}"`).join(", ");
  const description = escape(answers.description);
  const name = escape(answers.name);
  const short = description.slice(0, 120);
  const contents = `import { defineAppConfig } from "@minifactory/config";

export const appConfig = defineAppConfig({
  id: "${answers.slug}",
  name: "${name}",
  slug: "${answers.slug}",
  description: "${description}",
  botUsername: "YourBotUsername",
  productionUrl: "",
  theme: {
    accent: "${answers.accent}",
    radius: "16px",
    fontFamily:
      'system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
  },
  logo: "/logo.svg",
  supportContact: "",
  privacyUrl: "/privacy",
  termsUrl: "/terms",
  capabilities: [${capabilities}],
  limits: {
    anonymousUsage: false,
    features: {
      process: {
        freePerDay: 5,
        extraAfterAd: 1,
        premiumUnlimited: true,
        unlimited: false,
      },
    },
  },
  analytics: { enabled: true },
  monetization: { enabled: false, products: [] },
  listing: {
    shortDescription: "${short}",
    longDescription: "${description}",
    category: "utilities",
    keywords: ["${answers.slug}", "telegram", "minifactory"],
  },
  shell: {
    showUsage: true,
    showSettings: false,
    showShare: true,
    showPaywall: ${answers.capabilities.includes("payments") ? "true" : "false"},
  },
});
`;
  writeFileSync(join(targetDir, "app.config.ts"), contents);
}

function writeVercelConfig(targetDir: string, slug: string) {
  const contents = `${JSON.stringify(
    {
      framework: "nextjs",
      installCommand: "cd ../.. && pnpm install",
      buildCommand: `cd ../.. && pnpm --filter @minifactory/${slug} build`,
    },
    null,
    2,
  )}\n`;
  writeFileSync(join(targetDir, "vercel.json"), contents);
}

async function main() {
  const answers = await promptMissing(parseArgs(process.argv));
  const root = repoRoot();
  const templateDir = join(root, "apps/template");
  const targetDir = join(root, "apps", answers.slug);

  if (!existsSync(templateDir)) {
    throw new GeneratorError("apps/template is missing");
  }
  if (existsSync(targetDir)) {
    if (!answers.force) {
      throw new GeneratorError(`apps/${answers.slug} already exists. Pass --force to overwrite.`);
    }
    rmSync(targetDir, { recursive: true, force: true });
  }

  copyDir(templateDir, targetDir);
  writeAppConfig(targetDir, answers);
  writeVercelConfig(targetDir, answers.slug);

  const pkgPath = join(targetDir, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { name: string };
  pkg.name = `@minifactory/${answers.slug}`;
  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

  const envPath = join(targetDir, ".env.example");
  if (existsSync(envPath)) {
    let env = readFileSync(envPath, "utf8");
    env = env.replace("http://localhost:3000", "http://localhost:3001");
    writeFileSync(envPath, env);
  }

  const logoPath = join(targetDir, "public/logo.svg");
  if (existsSync(logoPath)) {
    const logo = readFileSync(logoPath, "utf8").replace("#2481cc", answers.accent);
    writeFileSync(logoPath, logo);
  }

  console.log(`Created ${relative(root, targetDir)}`);
  console.log(`Next: cp apps/${answers.slug}/.env.example apps/${answers.slug}/.env.local`);
  console.log(`Then: pnpm --filter @minifactory/${answers.slug} dev`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
